---
title: "Brownlows Bets"
author: "Anjolie Barrios"
date: "Year 2020"
output: 
  html_document:
    number_sections: true
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(tidyverse)
require(knitr)
```


<!-- We recommend you use git branches -- create a separate branch for each major section i.e. Introduction, Methods, Results, Inferential Results, and Discussion and Conclusions - leave the YAML block untouched until the final merge where you put in your own name !-->

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->

 At the first day of class there are 35 students in Math Statistics class and professor Brownlow always proposes this bet to his students "I will wager $2 to your bet of $1 that at least two people in today's class have  the same birthday.  He tells me he has made that bet 637 times so far. Where do you think his profits are? Discuss this in a markdown document
 
Report git commit structure:
There are 3 questions and there should be at least 3 separate commits, at least one dealing with each of the 3 questions.
1. What are the fair odds for a bet on matching birthdays in a 35 person class.
2. For what size class is a 2:1 odds bet fair.
3. How much money would Brownlow be expected to end up with if the bets went as described.

# What are the fair odds: Methods
<!--Decide on your methods:  In this section explain the approach you will take to attack the issue --- how will you decide on a likely estimate of professor Brownlow's earnings or losses after 637 bets. Also explain how you construct a 95% confidence interval about your estimate of his winnings !-->
When there 35 people in the class, there are 36 possibilities:  
P(0) = no one shares birthdays.  
P(1) = 1 person "shares" a birthday with themselves. In reality, no shares birthdays. 
P(2) = 2 people have shared birthdays.  
P(3) = 3 people have shared birthdays, and so on, until
P(35) = everyone has the same birthday.  
  
Prof. Barlow, however, is betting on AT LEAST two people having matching birthdays, so the chance we want to calculate is actually P(at least 2) or P(2+).  Knowing P(0,1) will complete the equation below.  
P(2+) = 1 - P(0,1), since P(2+) is the converse of P(0,1)  
  
To find P(0,1):    
There are exactly 365.24 days of the year, so the first person has a 1/365.24 chance of having a certain birthday. The next person has a 1/364.24 chance of a UNIQUE birthday (since 1 bday was already taken). When n = the number of students, the process continues to make this equation:  
P(0,1) = [365.24 * (365.24 - 1) * (365.24 - 2) ... (366.24 - n)] / (365.24)  
Note that part of the equation is 366.24 - n. This is a simplification of 365.24 - (n-1).  
  
After P(2+) is found for n = 35, the number of successful bets can be estimated using the number of total bets, which is 637. (Note that P(2+) is a value between 0 and 1.)  
Successful bets = P(2+) * 637  
  
For every success, he gets $2. For every fail, he looses $1. If S = number of successful bets and F = number of failed bets, then:  
2S - F = net amount of money gained/lost, in dollars.  

In order to calculate 95% confidence interval, we need to put the info into a dataset with these variables: n or No_ofStudents, P(0,1) or betFail_chance, P(2+) or betWin_chance, successfulBets, failedBets, and netProfit. 

##1. What are the fair odds for a bet on matching birthdays in a 35 person class?  
0.1858292 : 0.8141708 is the fair odds for a bet on matching birthdays, P(2+).  
This is because the fair odds of any P are (1-P):P. It can also be written as 1858292:8141708, rounded to ~19: ~81, and rounded again to be 1:4. 

# What size of class makes the 2:1 bet fair?  
<!--Explain and display the results of your method of coming up with the estimate of professor Brownlows betting profits!-->


# In the class and payoff as described what is a 95% confidence interval for Brownlow's earnings?
  
<!--Explain and display your method of coming up with a 95% confidence interval of  professor Brownlows winnings (or losings)-->


# Discussion and Conclusion

<!--Discussion and conclusion here.  If professor Brownlow is consistantly making or losing money how could he change his payout so that his profits center on zero?  Also discuss what size his class should be in order to have his current scheme balance at zero profit.!-->

